version: 2
updates:
  - package-ecosystem:  "npm"
    directory: "/dummy-frontend"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "dotnet-sdk"
    directory: "/dummy-api"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
